name: Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  asciidoc-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
    - run: npm install -g asciidoc-link-check
    - run: asciidoc-link-check *.adoc -c config.json
